/**
 * test_round_l.mjs
 * ------------------------------------------------------------
 * 今回(2026-07 続報その2)の6件の要望対応を検証する簡易ユニットテスト。
 *
 * 1. 「オンラインで2プレイヤーの時同じ面にいて、1人しか操作できず、面移動で
 *    相手の画面も切り替わる。スポーン地点も別で、独立して操作できるように」
 *    → CubeStage.generate()にhumansShareFaceオプションを追加し、
 *      オンライン時はfalseを渡して1人1面(独立)にする対応、
 *      NetworkSystem.send()がsenderClientIdを付与するようになった対応
 *      (「1人しか操作できない」不具合の直接原因)、オートマッチング時に
 *      待合ロビーのclientIdを対戦部屋にも引き継ぐようになった対応
 *      (ゲスト側が自分のplayerIdを解決できず、常にホストの画面に
 *      引っ張られていた不具合の原因)を検証する。
 * 2. 「面の切り替わり方がぐちゃぐちゃ。上から面移動したら縦回転で、横から
 *    面移動は横回転で画面が変わってほしい」→ Player.lastCrossDirection・
 *    NetworkProtocol経由の同期・CubeRenderer.rotateToFaceの
 *    転がり(tumble)+捻り(twist)の2段階回転への対応を検証する。
 * 3. 「トップ画面の画像が小さい。ブラウザ全体をデザインして」→
 *    index.htmlのfavicon/theme-color/背景・100dvh対応を検証する。
 * 4. 「トップ画面にもどった時前回のプレイ画面の最後が残ってる」→
 *    CubeRenderer.dispose()がcanvasを隠し、init()が再表示することを検証する。
 * 5. 「スタートのカウントダウンは無音にして」→ _startCountdown内で
 *    countdown_tick/countdown_go効果音を鳴らすコードが無くなったことを検証する。
 * ------------------------------------------------------------
 */
import fs from 'fs';

class FakeScene {
  constructor() {
    this.time = { now: 0, delayedCall: (_ms, _cb) => ({ remove: () => {} }) };
  }
}
globalThis.Phaser = {
  Scene: FakeScene,
  AUTO: 'AUTO',
  Scale: { FIT: 'FIT', CENTER_BOTH: 'CENTER_BOTH', RESIZE: 'RESIZE' },
  Input: { Keyboard: { KeyCodes: { SPACE: 'SPACE', ESC: 'ESC' } } },
};

let pass = 0;
let fail = 0;
function check(label, condition) {
  if (condition) {
    pass++;
    console.log(`  OK  ${label}`);
  } else {
    fail++;
    console.log(`  NG  ${label}`);
  }
}

const { CubeStage } = await import('./src/objects/CubeStage.js');
const { Player } = await import('./src/objects/Player.js');
const { BLOCK_TYPES, CUBE_FACE_NAMES } = await import('./src/constants/GameConstants.js');
const { serializePlayerState, applyPlayerState } = await import('./src/systems/NetworkProtocol.js');
const { NetworkSystem } = await import('./src/systems/NetworkSystem.js');

console.log('== 1. オンライン対戦: スポーン地点の独立・入力の到達 ==');
{
  const shared = new CubeStage(11, 11);
  shared.generate(3, 2); // 既定(humansShareFace省略=true): 従来通りローカルPVP向けの挙動
  const sharedPositions = shared.getStartPositions();
  check(
    '既定(humansShareFace省略)では、従来通り人間2人が同じ面からスタートする(ローカルPVPの回帰防止)',
    sharedPositions[0].face === sharedPositions[1].face
  );

  const independent = new CubeStage(11, 11);
  independent.generate(3, 2, { humansShareFace: false });
  const independentPositions = independent.getStartPositions();
  check(
    'humansShareFace:falseでは、人間2人が別々の面からスタートする(オンライン対戦のスポーン地点分離)',
    independentPositions[0].face !== independentPositions[1].face
  );
  check(
    '独立配置でも参加者全員(人間+AI)が別々の面に1人ずつ配置される',
    new Set(independentPositions.map((p) => p.face)).size === independentPositions.length
  );

  const gameSceneSrc = fs.readFileSync('src/scenes/GameScene.js', 'utf8');
  check(
    'GameSceneがオンライン時にhumansShareFace:falseを渡している(ローカルPVPではtrueのまま)',
    /this\.stage\.generate\(totalParticipants, this\.config\.humanCount, \{\s*\n\s*humansShareFace: this\.config\.mode !== 'online',/.test(
      gameSceneSrc
    )
  );
}

console.log('\n== 2. オンライン対戦: NetworkSystemのsenderClientId付与・clientId引き継ぎ ==');
{
  const net = new NetworkSystem();
  let sentPayload = null;
  net.channel = { send: ({ payload }) => { sentPayload = payload; } };
  net.send({ type: 'input', mode: 'move', playerId: 2, up: true });

  check('send()が呼び出し元のmessageの内容をそのまま含める', sentPayload.type === 'input' && sentPayload.playerId === 2);
  check(
    'send()が送信元識別子senderClientIdを自動付与する(以前は付与されず、ホストが常にゲスト入力を無視していた不具合の修正)',
    sentPayload.senderClientId === net.clientId
  );

  const reused = new NetworkSystem('c_existing_123');
  check('NetworkSystemのコンストラクタに既存のclientIdを渡すと、それがそのまま使われる', reused.clientId === 'c_existing_123');

  const autoGenerated = new NetworkSystem();
  check('clientIdを渡さない場合は自動生成される(空でない文字列)', typeof autoGenerated.clientId === 'string' && autoGenerated.clientId.length > 0);

  const lobbySrc = fs.readFileSync('src/scenes/OnlineLobbyScene.js', 'utf8');
  check(
    'オートマッチングのリーダーが、対戦部屋用NetworkSystemに待合ロビーのclientIdを引き継ぐ(不一致でゲストが自分を解決できない不具合の修正)',
    /gameNetwork = new NetworkSystem\(this\._autoMatchNetwork\.clientId\);\s*\n\s*roomCode = await gameNetwork\.createRoom\(\);/.test(
      lobbySrc
    )
  );
  check(
    'オートマッチングの参加者側も、対戦部屋用NetworkSystemに待合ロビーのclientIdを引き継ぐ',
    /gameNetwork = new NetworkSystem\(this\._autoMatchNetwork\.clientId\);\s*\n\s*await gameNetwork\.joinRoom\(msg\.roomCode\);/.test(
      lobbySrc
    )
  );
}

console.log('\n== 3. 面移動の回転方向(lastCrossDirection)の記録・同期 ==');
{
  const cube = new CubeStage(11, 11);
  cube.generate(1, 1);
  const frontStage = cube.getFaceStage('FRONT');
  const rightStage = cube.getFaceStage('RIGHT');
  // 生成時のランダム性を排除し、面をまたぐ経路を確定的に通行可能にする
  // (row=1は柱判定col%2===0&&row%2===0に該当しないため、どのcolでも柱にならない)。
  frontStage.setBlockType(frontStage.cols - 1, 1, BLOCK_TYPES.EMPTY);
  rightStage.setBlockType(0, 1, BLOCK_TYPES.EMPTY);

  const scene = new FakeScene();
  const player = new Player(scene, cube, 'FRONT', frontStage.cols - 1, 1, { playerId: 1 });

  check('生成直後はlastCrossDirectionがnull', player.lastCrossDirection === null);

  const movedWithinFace = player.tryMove('down'); // 面内の移動(まだ端に達していない可能性があるがcrossしない前提)
  // 面内移動が成功してもlastCrossDirectionは更新されない(crossしていないため)
  if (movedWithinFace) {
    check('面をまたがない移動ではlastCrossDirectionが更新されない', player.lastCrossDirection === null);
  } else {
    check('面をまたがない移動が失敗した場合もlastCrossDirectionはnullのまま', player.lastCrossDirection === null);
  }

  const crossed = player.tryMove('right');
  check('面の端から隣接面へ実際にまたげる(テスト条件が正しい)', crossed === true && player.face === 'RIGHT');
  check('面をまたいだ場合、lastCrossDirectionに実際の移動方向が記録される', player.lastCrossDirection === 'right');

  const state = serializePlayerState(player);
  check('serializePlayerStateがlastCrossDirectionを含める', state.lastCrossDirection === 'right');

  const mirror = new Player(scene, cube, 'FRONT', frontStage.cols - 1, 1, { playerId: 1 });
  applyPlayerState(mirror, state, 1000);
  check(
    'applyPlayerStateがミラー側(ゲスト)のPlayerにもlastCrossDirectionを反映する(ゲスト側のカメラ回転演出用)',
    mirror.lastCrossDirection === 'right'
  );
}

console.log('\n== 4. CubeRendererの回転軸統一(転がり+捻りの2段階)・canvas残像対策 ==');
{
  const rendererSrc = fs.readFileSync('src/systems/CubeRenderer.js', 'utf8');

  check(
    '固定軸(画面の水平方向a・垂直方向b)を保持している',
    /this\._axisA = a\.clone\(\);/.test(rendererSrc) && /this\._axisB = b\.clone\(\);/.test(rendererSrc)
  );
  check(
    '移動方向(up/down/left/right)ごとに固定のちょうど90度回転を用意している',
    /_directionRollQuaternions = \{/.test(rendererSrc) &&
      /up: new THREE\.Quaternion\(\)\.setFromAxisAngle\(this\._axisA, Math\.PI \/ 2\)/.test(rendererSrc) &&
      /down: new THREE\.Quaternion\(\)\.setFromAxisAngle\(this\._axisA, -Math\.PI \/ 2\)/.test(rendererSrc) &&
      /left: new THREE\.Quaternion\(\)\.setFromAxisAngle\(this\._axisB, Math\.PI \/ 2\)/.test(rendererSrc) &&
      /right: new THREE\.Quaternion\(\)\.setFromAxisAngle\(this\._axisB, -Math\.PI \/ 2\)/.test(rendererSrc)
  );
  check('最短経路になるよう符号を揃えるヘルパー(_ensureShortestPath)がある', /_ensureShortestPath\(from, to\)/.test(rendererSrc));
  check(
    'rotateToFaceがdirection引数を受け取り、転がり(tumble)先の中間姿勢qMidを計算する',
    /rotateToFace\(face, direction, now\)/.test(rendererSrc) && /const qMid = roll90\.clone\(\)\.multiply\(qFrom\);/.test(rendererSrc)
  );
  check(
    '転がり(90度固定)と捻り(0〜180度)の所要時間を回転量に比例して配分している',
    /const TUMBLE_ANGLE = Math\.PI \/ 2;/.test(rendererSrc) &&
      /this\._rotationTumbleFrac = twistAngle < 1e-4 \? 1 : TUMBLE_ANGLE \/ \(TUMBLE_ANGLE \+ twistAngle\);/.test(rendererSrc)
  );
  check(
    'dispose()が描画バッファをクリアし、canvasを非表示にする(前回の対戦画面が残る不具合の修正)',
    /this\.renderer\.clear\(\);/.test(rendererSrc) && /this\.canvas\.style\.visibility = 'hidden';/.test(rendererSrc)
  );
  check('init()が(前回dispose()で隠された)canvasを再び表示する', /if \(this\.canvas\) this\.canvas\.style\.visibility = 'visible';/.test(rendererSrc));

  // 【2026-07リファクタ】「移動の面がかわっていない」報告の調査の一環で、
  // 元々_updateGuest・update()の2箇所に重複していたcubeRenderer.
  // syncPlayers/rotateToFace/render呼び出しを、共通の_renderCubeStage(time)
  // ヘルパーに1本化した(万一の実行時例外で3D描画全体が固まるのを防ぐ
  // try/catchも追加)。そのため呼び出し箇所自体は1つになったが、
  // ホスト側update()・ゲスト側_updateGuestの両方からこのヘルパーが
  // 呼ばれていることを確認する。
  const gameSceneSrc = fs.readFileSync('src/scenes/GameScene.js', 'utf8');
  const rotateCalls = gameSceneSrc.match(/cubeRenderer\.rotateToFace\(this\.humanPlayer\.face, this\.humanPlayer\.lastCrossDirection, time\)/g) ?? [];
  check(
    'rotateToFaceへlastCrossDirectionを渡す呼び出しが共通ヘルパー_renderCubeStage内に1本化されている',
    rotateCalls.length === 1 && /_renderCubeStage\(time\)\s*\{/.test(gameSceneSrc),
  );
  const helperCallSites = gameSceneSrc.match(/this\._renderCubeStage\(time\);/g) ?? [];
  check(
    '_renderCubeStageがホスト側update()・ゲスト側_updateGuestの両方(2箇所)から呼ばれている',
    helperCallSites.length === 2,
  );
  check(
    '_renderCubeStageは万一の実行時例外を握りつぶし、3D描画全体が固まらないようにする(try/catch)',
    /try \{\s*\n\s*this\.cubeRenderer\.syncPlayers/.test(gameSceneSrc) && /} catch \(e\) \{/.test(gameSceneSrc),
  );
}

console.log('\n== 5. スタートのカウントダウンを無音化 ==');
{
  const gameSceneSrc = fs.readFileSync('src/scenes/GameScene.js', 'utf8');
  const countdownBlockMatch = gameSceneSrc.match(/_startCountdown\(\) \{[\s\S]*?\n  \}/);
  check('_startCountdownメソッドが見つかる(テスト自体の前提条件)', !!countdownBlockMatch);
  const countdownBlock = countdownBlockMatch ? countdownBlockMatch[0] : '';
  check(
    '_startCountdown内でcountdown_tick/countdown_goの効果音を鳴らすコードが無い(無音化)',
    !/soundSystem\.playSE\(label === 'START' \? 'countdown_go' : 'countdown_tick'\)/.test(countdownBlock)
  );
  check('カウントダウン終了後のBGM再生(soundSystem.playBGM(\'game\'))は引き続き行われる', /soundSystem\.playBGM\('game'\)/.test(countdownBlock));
}

console.log('\n== 6. 「ブラウザ全体をデザインして」対応(index.html) ==');
{
  const html = fs.readFileSync('index.html', 'utf8');
  check('favicon(32x32)が設定されている', /<link rel="icon" type="image\/png" sizes="32x32" href="assets\/images\/title\/favicon-32\.png" \/>/.test(html));
  check('apple-touch-iconが設定されている', /<link rel="apple-touch-icon"/.test(html));
  check('theme-colorが設定されている', /<meta name="theme-color" content="#[0-9a-fA-F]{6}" \/>/.test(html));
  check('スマホの動的ツールバー対策として100dvhも指定されている', /height: 100dvh;/.test(html));
  check('favicon画像ファイルが実際に存在する', fs.existsSync('assets/images/title/favicon-32.png') && fs.existsSync('assets/images/title/favicon-180.png'));
}

console.log(`\n合計: ${pass} 件成功 / ${fail} 件失敗`);
if (fail > 0) process.exit(1);
